package com.robbyari.tokosepatu.model

import com.robbyari.tokosepatu.R

object FakeShoesDataSource {
    val dummyShoes = listOf(
        Shoes(1, R.drawable.air_zoom_victory_tour_3, "Air Zoom Victory", "Do you ever daydream about Georgia in the spring? We do. With its peach-fuzz tones complementing a hessian sack-like base, this version is perfect for a long stroll through a warm, inviting Southern breeze. It offers robust comfort, unreal energy return and brand-new spikes, whether you're swinging through or playing through en route to 36. Radiant bright colours and extra-juicy green goodness throughout remind you to keep it fresh, always.",3169000, "4.9"),
        Shoes(2, R.drawable.air_jordan_low_se, "Air Jordan Low SE", "Get into some summery fun in your new fave AJ1s. Made with a combination of suede and canvas, this pair gives you the comfort you know and love with a seasonal update.",1859000, "4.7"),
        Shoes(3, R.drawable.air_max_90, "Air Max 90", "Lace up and feel the legacy. Produced at the cross section of art, music and culture, this champion running shoe helped define the '90s. Worn by presidents, revolutionised through collabs and celebrated through rare colourways, its striking visuals, Waffle outsole and exposed Air cushioning keep it alive and well.",1869000, "4.4"),
        Shoes(4, R.drawable.pegasus_40_premium, "Pegasus 40 Premium", "A springy ride for every run, the Peg's familiar, just-for-you feel returns to help you accomplish your goals. This version has the same responsiveness and neutral support you love but with improved comfort in those sensitive areas of your foot, like the arch and toes. Whether you're logging long marathon miles, squeezing in a speed session before the sun goes down or hopping into a spontaneous group jaunt, it's still the established road runner you can put your faith in, day after day, run after run.",2199000, "4.8"),
        Shoes(5, R.drawable.tech_hera, "Tech Hera", "The Tech Hera is here to fulfil all of your chunky sneaker wishes. The wavy lifted midsole and suede accents level up your look while keeping you comfortable. Its durable design holds up beautifully to everyday wear—which is perfect, because you'll definitely want to wear these every day.",1729000 ,"4.6"),
        Shoes(6, R.drawable.react_pegasus_trail_4_se, "React Pegasus Trail 4 SE", "Running is your daily ritual, taking you from road to trail as you seek out new adventures and goals. Let the Nike React Pegasus Trail 4 take you there and back again with its supportive and springy feel. Underfoot traction keeps you going over rocky terrain, while still providing a smooth ride for the road. Midfoot support is controlled by the laces, letting you find the right fit and feel. Sharp, bright hues complement dark-room-colour neutrals, speaking to an inclusive world where digital and physical coexist in harmony.",2099000, "4.3"),
        Shoes(7, R.drawable.react_infinity_3, "React Infinity 3", "Still 1 of our most tested shoes, made to help you stay after those lofty running goals. The Nike React Infinity Run 3 feels soft and stable, providing a smooth ride that will carry you through routes—both long and short. A breathable upper is made to feel contained, yet flexible. We even added more cushioning around the heel and ankle for a supportive sensation.",2669000, "4.6"),
        Shoes(8, R.drawable.sb_force_58, "SB Force 58", "The latest and greatest innovation to hit the streets, the Nike SB Force 58 gives you the durability of a cupsole with the flexibility of a vulcanised shoe. Made from canvas and suede and finished with perforations, the whole look is infused with heritage basketball DNA.",1099000, "4.4"),
        Shoes(9, R.drawable.air_jordan_2_retro_low_titan, "Air Jordan 2 Retro Low Titan", "Spread the love. Tell the stories. Step into greatness. Teaming up with Filipino basketball collective, Titan, this timeless take on the AJ2 bridges past, present and future. With an unquestionable passion for the game, designer Chi Loyzaga-Gibbs sets the stage with an honorary look that's rooted to the beloved 1954 Filipino national team. Premium suede, richly textured corduroy and crisp leather are combined with a speckled midsole, while original artwork connects you to the hoops heartbeat no matter where you are.",2808000, "4.8"),
        Shoes(10, R.drawable.nike_dunk_low_by_you, "Dunk Low By You", "Take your game anywhere with the Nike Dunk Low By You. Created for the hardwood but taken to the streets, the '80s b-ball icon returns with a new design thought up by you. Select a Nike Grind, Gum or standard outsole. Pick your favourite colours. Then seal the deal with a personalised inscription on the back.",2099000, "4.7"),
    )
}