package com.robbyari.tokosepatu.model

import com.robbyari.tokosepatu.R

object FakeShoesDataSource {
    val dummyShoes = listOf(
        Shoes(1, R.drawable.air_force_1_sculpt_shoes, "Air Force 1 Sculp Shoes", "From hoops staple to urban street legend, the Nike AF-1 React takes another step forward into shoe iconography. Amplified features from the outsole to the branding add dramatic expression to the storied look while Nike React tech assists with a smooth ride. Stand out to fit in.",2420000, "4.5"),
        Shoes(2, R.drawable.air_force_1_sculpt_shoes, "Air Force 1 Sculp Shoes", "From hoops staple to urban street legend, the Nike AF-1 React takes another step forward into shoe iconography. Amplified features from the outsole to the branding add dramatic expression to the storied look while Nike React tech assists with a smooth ride. Stand out to fit in.",2420000, "4.5"),
        Shoes(3, R.drawable.air_force_1_sculpt_shoes, "Air Force 1 Sculp Shoes", "From hoops staple to urban street legend, the Nike AF-1 React takes another step forward into shoe iconography. Amplified features from the outsole to the branding add dramatic expression to the storied look while Nike React tech assists with a smooth ride. Stand out to fit in.",2420000, "4.5"),
        Shoes(4, R.drawable.air_force_1_sculpt_shoes, "Air Force 1 Sculp Shoes", "From hoops staple to urban street legend, the Nike AF-1 React takes another step forward into shoe iconography. Amplified features from the outsole to the branding add dramatic expression to the storied look while Nike React tech assists with a smooth ride. Stand out to fit in.",2420000, "4.5"),
        Shoes(5, R.drawable.air_force_1_sculpt_shoes, "Air Force 1 Sculp Shoes", "From hoops staple to urban street legend, the Nike AF-1 React takes another step forward into shoe iconography. Amplified features from the outsole to the branding add dramatic expression to the storied look while Nike React tech assists with a smooth ride. Stand out to fit in.",2420000, "4.5"),
        Shoes(6, R.drawable.air_force_1_sculpt_shoes, "Air Force 1 Sculp Shoes", "From hoops staple to urban street legend, the Nike AF-1 React takes another step forward into shoe iconography. Amplified features from the outsole to the branding add dramatic expression to the storied look while Nike React tech assists with a smooth ride. Stand out to fit in.",2420000, "4.5"),
        Shoes(7, R.drawable.air_force_1_sculpt_shoes, "Air Force 1 Sculp Shoes", "From hoops staple to urban street legend, the Nike AF-1 React takes another step forward into shoe iconography. Amplified features from the outsole to the branding add dramatic expression to the storied look while Nike React tech assists with a smooth ride. Stand out to fit in.",2420000, "4.5"),
        Shoes(8, R.drawable.air_force_1_sculpt_shoes, "Air Force 1 Sculp Shoes", "From hoops staple to urban street legend, the Nike AF-1 React takes another step forward into shoe iconography. Amplified features from the outsole to the branding add dramatic expression to the storied look while Nike React tech assists with a smooth ride. Stand out to fit in.",2420000, "4.5"),
        Shoes(9, R.drawable.air_force_1_sculpt_shoes, "Air Force 1 Sculp Shoes", "From hoops staple to urban street legend, the Nike AF-1 React takes another step forward into shoe iconography. Amplified features from the outsole to the branding add dramatic expression to the storied look while Nike React tech assists with a smooth ride. Stand out to fit in.",2420000, "4.5"),
        Shoes(10, R.drawable.air_force_1_sculpt_shoes, "Air Force 1 Sculp Shoes", "From hoops staple to urban street legend, the Nike AF-1 React takes another step forward into shoe iconography. Amplified features from the outsole to the branding add dramatic expression to the storied look while Nike React tech assists with a smooth ride. Stand out to fit in.",2420000, "4.5"),
    )
}